### ISSUE TITLE
Future changes in code referenced from migrations.

### ISSUE THREAD

**Issue by vic** [midas/phil_columns-ex#1]
Hi, I'm curious about how to handle code changes in phil_columns migrations. Your project reminds me of when people wrote Rails migrations that actually invoked some ruby logic (instead of doing plain db migrations). The problem with this is the code referenced by the migration might change in the future, and will render the migration's code invalid.

Suppose you write a migration that creates a couple of users:

```elixir
def up do
   SomeLogic.create_user(:homer)
   SomeLogic.create_user(:bart)
end
```

Six months later if someone tries to remove or change the number of params for `create_user`.  The old migration code will no longer work. One alternative would be to use a macro to capture
the code and only execute it if the migration needs to be run. However this only postpones the problem as you wouldnt notice the error until a new developer tries to run all the historic migrations.

```elixir
up do # only compiled if the migration needs to be run
   SomeLogic.create_user(:homer)
   SomeLogic.create_user(:bart)
end
```

Another approach would be to recommend users to write all the logic in the migration itself, (even at the price of duplicating some logic) for keeping each migration as an immutable unit of code.

Another even wilder approach would be to make migrations git-aware (somehow save the commit) and checkout it somewhere just to execute that version of the code. Dont believe this could be a sane option but just thinking out loud.

**Comment by midas** [comment]
Hi vic,

You are correct in pointing out phil_columns suffers from the same issue.  I usually just refactor my seeds as they are broken by features or bug fixes.  It has created much less friction for me than I would have assumed.  I also usually just use low level operations in seeds so the chances of breakage are reduced (at the expense of possible duplication).
