### ISSUE TITLE
Can you please bump the inflex library dependency to 2.x

### ISSUE THREAD

**Issue by dlobo** [midas/phil_columns-ex#5]
Thanx. I can submit a PR if needed. Just starting to use this package, and I needed to fork it to accomodate another library (ex_twilio)

thanx

**Comment by dlobo** [comment]
I've created a PR for this. Would highly appreciate it if you could merge and do a new release 👍 

thanx

**Comment by midas** [comment]
Done: https://hex.pm/packages/phil_columns/3.1.0.

Thanks!

**Comment by dlobo** [comment]
awesome, thank you so much 👍
